--local ReplicatedStorage = game:GetService("ReplicatedStorage")

--local Items = require(ReplicatedStorage.Shared.Info.Items)

--local ItemTypes = require(ReplicatedStorage.Shared.Info.Items.ItemTypes)


--local ItemUtil = {}

--function ItemUtil.getItemInfoFromKey(key: string): ItemTypes.BaseItem?
--    for _, itemList in pairs(Items) do
--        local itemInfo = itemList[key]
--        if itemInfo then
--            return itemInfo
--        end
--    end
--    warn("[ItemUtil] No item found for key:", key)
--    return nil
--end

--return ItemUtil

return {}