local EggMutations = {
	Simple = {
		HatchTime = 10,
		SkipRobuxCost = 0,

		Mutations = {
			Default     = { Cost = 25,       FusionChance = nil },
			Silver      = { Cost = 50,       FusionChance = 70.00 },
			Gold        = { Cost = 100,      FusionChance = 15.00 },
			Diamond     = { Cost = 200,      FusionChance = 7.00 },
			Rainbow     = { Cost = 400,      FusionChance = 3.50 },
			Thunder     = { Cost = 800,      FusionChance = 1.80 },
			Saiyan      = { Cost = 1600,     FusionChance = 1.00 },
			Conqueror   = { Cost = 3200,     FusionChance = 0.60 },
			Corrupted   = { Cost = 6400,     FusionChance = 0.40 },
			Galaxy      = { Cost = 12800,    FusionChance = 0.35 },
			Divine      = { Cost = 25600,    FusionChance = 0.25 },
		}
	},

	Good = {
		HatchTime = 30,
		SkipRobuxCost = 9,

		Mutations = {
			Default     = { Cost = 500,      FusionChance = nil },
			Silver      = { Cost = 1000,     FusionChance = 70.00 },
			Gold        = { Cost = 2000,     FusionChance = 15.00 },
			Diamond     = { Cost = 4000,     FusionChance = 7.00 },
			Rainbow     = { Cost = 8000,     FusionChance = 3.50 },
			Thunder     = { Cost = 16000,    FusionChance = 1.80 },
			Saiyan      = { Cost = 32000,    FusionChance = 1.00 },
			Conqueror   = { Cost = 64000,    FusionChance = 0.60 },
			Corrupted   = { Cost = 128000,   FusionChance = 0.40 },
			Galaxy      = { Cost = 256000,   FusionChance = 0.35 },
			Divine      = { Cost = 512000,   FusionChance = 0.25 },
		}
	},

	Rare = {
		HatchTime = 60,
		SkipRobuxCost = 19,

		Mutations = {
			Default     = { Cost = 25000,    FusionChance = nil },
			Silver      = { Cost = 50000,    FusionChance = 70.00 },
			Gold        = { Cost = 100000,   FusionChance = 15.00 },
			Diamond     = { Cost = 200000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 400000,   FusionChance = 3.50 },
			Thunder     = { Cost = 800000,   FusionChance = 1.80 },
			Saiyan      = { Cost = 1600000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 3200000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 6400000,  FusionChance = 0.40 },
			Galaxy      = { Cost = 12800000, FusionChance = 0.35 },
			Divine      = { Cost = 25600000, FusionChance = 0.25 },
		}
	},

	Cracked = {
		HatchTime = 120,
		SkipRobuxCost = 29,

		Mutations = {
			Default     = { Cost = 50000,    FusionChance = nil },
			Silver      = { Cost = 100000,   FusionChance = 70.00 },
			Gold        = { Cost = 200000,   FusionChance = 15.00 },
			Diamond     = { Cost = 400000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 800000,   FusionChance = 3.50 },
			Thunder     = { Cost = 1600000,  FusionChance = 1.80 },
			Saiyan      = { Cost = 3200000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 6400000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 12800000, FusionChance = 0.40 },
			Galaxy      = { Cost = 25600000, FusionChance = 0.35 },
			Divine      = { Cost = 51200000, FusionChance = 0.25 },
		}
	},

	Ancient = {
		HatchTime = 300,
		SkipRobuxCost = 49,

		Mutations = {
			Default     = { Cost = 150000,    FusionChance = nil },
			Silver      = { Cost = 300000,    FusionChance = 70.00 },
			Gold        = { Cost = 600000,    FusionChance = 15.00 },
			Diamond     = { Cost = 1200000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 2400000,   FusionChance = 3.50 },
			Thunder     = { Cost = 4800000,   FusionChance = 1.80 },
			Saiyan      = { Cost = 9600000,   FusionChance = 1.00 },
			Conqueror   = { Cost = 19200000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 38400000,  FusionChance = 0.40 },
			Galaxy      = { Cost = 76800000,  FusionChance = 0.35 },
			Divine      = { Cost = 153600000, FusionChance = 0.25 },
		}
	},

	Hell = {
		HatchTime = 600,
		SkipRobuxCost = 99,

		Mutations = {
			Default     = { Cost = 750000,    FusionChance = nil },
			Silver      = { Cost = 1500000,   FusionChance = 70.00 },
			Gold        = { Cost = 3000000,   FusionChance = 15.00 },
			Diamond     = { Cost = 6000000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 12000000,  FusionChance = 3.50 },
			Thunder     = { Cost = 24000000,  FusionChance = 1.80 },
			Saiyan      = { Cost = 48000000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 96000000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 192000000, FusionChance = 0.40 },
			Galaxy      = { Cost = 384000000, FusionChance = 0.35 },
			Divine      = { Cost = 768000000, FusionChance = 0.25 },
		}
	},

	Celest = {
		HatchTime = 1200,
		SkipRobuxCost = 149,

		Mutations = {
			Default     = { Cost = 4000000,    FusionChance = nil },
			Silver      = { Cost = 8000000,    FusionChance = 70.00 },
			Gold        = { Cost = 16000000,   FusionChance = 15.00 },
			Diamond     = { Cost = 32000000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 64000000,   FusionChance = 3.50 },
			Thunder     = { Cost = 128000000,  FusionChance = 1.80 },
			Saiyan      = { Cost = 256000000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 512000000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 1024000000, FusionChance = 0.40 },
			Galaxy      = { Cost = 2048000000, FusionChance = 0.35 },
			Divine      = { Cost = 4096000000, FusionChance = 0.25 },
		}
	},
	
	-- this needs to be adjusted
	Exclusive = {
		HatchTime = 300,
		SkipRobuxCost = 49,

		Mutations = {
			Default     = { Cost = 4000000,    FusionChance = nil },
			Silver      = { Cost = 8000000,    FusionChance = 70.00 },
			Gold        = { Cost = 16000000,   FusionChance = 15.00 },
			Diamond     = { Cost = 32000000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 64000000,   FusionChance = 3.50 },
			Thunder     = { Cost = 128000000,  FusionChance = 1.80 },
			Saiyan      = { Cost = 256000000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 512000000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 1024000000, FusionChance = 0.40 },
			Galaxy      = { Cost = 2048000000, FusionChance = 0.35 },
			Divine      = { Cost = 4096000000, FusionChance = 0.25 },
		}
	},
	
	-- this needs to be adjusted
	["Halloween Egg"] = {
		HatchTime = 300,
		SkipRobuxCost = 49,

		Mutations = {
			Default     = { Cost = 4000000,    FusionChance = nil },
			Silver      = { Cost = 8000000,    FusionChance = 70.00 },
			Gold        = { Cost = 16000000,   FusionChance = 15.00 },
			Diamond     = { Cost = 32000000,   FusionChance = 7.00 },
			Rainbow     = { Cost = 64000000,   FusionChance = 3.50 },
			Thunder     = { Cost = 128000000,  FusionChance = 1.80 },
			Saiyan      = { Cost = 256000000,  FusionChance = 1.00 },
			Conqueror   = { Cost = 512000000,  FusionChance = 0.60 },
			Corrupted   = { Cost = 1024000000, FusionChance = 0.40 },
			Galaxy      = { Cost = 2048000000, FusionChance = 0.35 },
			Divine      = { Cost = 4096000000, FusionChance = 0.25 },
		}
	},
}

return EggMutations