local MutationInfo = {
	["Default"] = {
		Level = "Default",
		CPSMultiplier = 1,
		CostMultiplier = 1,
	},

	["Silver"] = {
		Level = "Silver",
		CPSMultiplier = 2,
		CostMultiplier = 10,
	},

	["Gold"] = {
		Level = "Gold",
		CPSMultiplier = 4,
		CostMultiplier = 18,
	},

	["Diamond"] = {
		Level = "Diamond",
		CPSMultiplier = 8,
		CostMultiplier = 34,
	},

	["Rainbow"] = {
		Level = "Rainbow",
		CPSMultiplier = 16,
		CostMultiplier = 66,
	},

	["Thunder"] = {
		Level = "Thunder",
		CPSMultiplier = 32,
		CostMultiplier = 130,
	},

	["Saiyan"] = {
		Level = "Saiyan",
		CPSMultiplier = 64,
		CostMultiplier = 258,
	},

	["Conqueror"] = {
		Level = "Conqueror",
		CPSMultiplier = 128,
		CostMultiplier = 514,
	},

	["Corrupted"] = {
		Level = "Corrupted",
		CPSMultiplier = 256,
		CostMultiplier = 1026,
	},

	["Galaxy"] = {
		Level = "Galaxy",
		CPSMultiplier = 512,
		CostMultiplier = 2050,
	},

	["Divine"] = {
		Level = "Divine",
		CPSMultiplier = 1024,
		CostMultiplier = 4098,
	},
}

return MutationInfo