local Constants = {}

--Constants.GroupReward = {
--	Cash = 5000,
--	Candy = 5,
	
--}

--Constants.XPGain = {
--    BlockPlace = 1,
--    PlayerKill = 10,
--}

--Constants.CoinGain = {
--    BlockPlace = 1,
--    PlayerKill = 15,
--    Win = 100,
--}

--Constants.SecondsInAMinute = 60
--Constants.SecondsInAnHour = Constants.SecondsInAMinute * 60
--Constants.SecondsInADay = Constants.SecondsInAnHour * 24

return Constants